export enum MITT_KEY_ENUM {
  /** 头部触发事件 */
  HEADER_SELECT_EVENT = 'HEADER_SELECT_EVENT',
  CHANGE_TO_HOME = 'CHANGE_TO_HOME',
  CHANGE_TO_BUSINESS = 'CHANGE_TO_BUSINESS',
  CHANGE_TO_DATA = 'CHANGE_TO_DATA',
  CHANGE_TO_TECHNOLOGY = 'CHANGE_TO_TECHNOLOGY',
  CHANGE_TO_QUALITY = 'CHANGE_TO_QUALITY',
  CHANGE_TO_ABOUT = 'CHANGE_TO_ABOUT',

}
